import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import ClientJokes from "../components/ClientJokes";
import config from "@/config";
import ReduxProviders from "@/redux/provider";
import MainLayout from "@/layouts/MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: config.appName,
    template: `${config.appName} | %s`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProviders>
          <MainLayout>
            <NavBar />
            {children}
          </MainLayout>
        </ReduxProviders>
        {/* <ClientJokes /> */}
      </body>
    </html>
  );
}
